name: flutter_ort_plugin_example
description: "Demonstrates how to use the flutter_ort_plugin plugin."
publish_to: 'none'
version: 1.0.1+1
environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter

  flutter_ort_plugin:

    path: ../

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  device_info_plus: ^9.1.2
  camera: ^0.11.0+2
  image: ^4.3.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/mnist/
   - assets/mnist/test_data_set_0/
   - assets/yolo11.onnx
   - assets/yolo11.ort
   - assets/street.mp4
